@startuml
actor "Client" as Client
usecase "ViewProduct" as ViewProduct 
usecase "AddProductToCart" as AddProduct
usecase "MakeOrder" as MakeOrder
usecase "Login" as Login

left to right direction
Client --> ViewProduct
Client --> MakeOrder
MakeOrder <-- Login: <<include>>
AddProduct <-- Login: <<include>>
@enduml